// <auto-generated />
using System;
using Fort.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fort.Migrations
{
    [DbContext(typeof(FortDbContext))]
    [Migration("20181224100842_teamCoef")]
    partial class teamCoef
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-preview1-35029")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Fort.Database.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Army");

                    b.Property<int?>("Grow");

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<string>("OwnerId")
                        .HasMaxLength(5);

                    b.Property<int>("X");

                    b.Property<int>("Y");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Fort.Database.Entities.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("At");

                    b.Property<string>("Level")
                        .HasMaxLength(30);

                    b.Property<string>("Message")
                        .HasMaxLength(200);

                    b.Property<string>("Player")
                        .HasMaxLength(10);

                    b.Property<string>("StackTrace");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Fort.Database.Entities.Path", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("SourceId");

                    b.Property<int>("TargetId");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.HasIndex("TargetId");

                    b.ToTable("Paths");
                });

            modelBuilder.Entity("Fort.Database.Entities.Round", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("EndsAt");

                    b.Property<string>("Note")
                        .HasMaxLength(1000);

                    b.Property<int>("RoundNumber");

                    b.Property<DateTime?>("StartsAt");

                    b.HasKey("Id");

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("Fort.Database.Entities.Team", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5);

                    b.Property<double>("ArmyStrengthCoef");

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<int?>("PopulationGrowth");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Fort.Database.Entities.Turn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Amount");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int?>("ModifiedAmount");

                    b.Property<int>("RoundId");

                    b.Property<int>("SourceCityId");

                    b.Property<int>("TargetCityId");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(5);

                    b.HasKey("Id");

                    b.HasIndex("RoundId");

                    b.HasIndex("SourceCityId");

                    b.HasIndex("TargetCityId");

                    b.HasIndex("UserId");

                    b.ToTable("Turns");
                });

            modelBuilder.Entity("Fort.Database.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5);

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(100);

                    b.Property<bool>("IsAdmin");

                    b.Property<string>("TeamId")
                        .HasMaxLength(5);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Fort.Database.Entities.City", b =>
                {
                    b.HasOne("Fort.Database.Entities.User", "Owner")
                        .WithMany("Cities")
                        .HasForeignKey("OwnerId");
                });

            modelBuilder.Entity("Fort.Database.Entities.Path", b =>
                {
                    b.HasOne("Fort.Database.Entities.City", "Source")
                        .WithMany("SourceToPaths")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fort.Database.Entities.City", "Target")
                        .WithMany("TargetToPaths")
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Fort.Database.Entities.Turn", b =>
                {
                    b.HasOne("Fort.Database.Entities.Round", "Round")
                        .WithMany("Turns")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fort.Database.Entities.City", "SourceCity")
                        .WithMany("SourceToTurns")
                        .HasForeignKey("SourceCityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fort.Database.Entities.City", "TargetCity")
                        .WithMany("TargetToTurns")
                        .HasForeignKey("TargetCityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fort.Database.Entities.User", "User")
                        .WithMany("Turns")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Fort.Database.Entities.User", b =>
                {
                    b.HasOne("Fort.Database.Entities.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId");
                });
#pragma warning restore 612, 618
        }
    }
}
