// <auto-generated />
using System;
using Fort.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fort.Migrations
{
    [DbContext(typeof(FortDbContext))]
    [Migration("20200404124957_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Fort.Database.Entities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("DefenceCoef");

                    b.Property<double>("PopulationGrowCoef");

                    b.Property<int>("X");

                    b.Property<int>("Y");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Fort.Database.Entities.CityOccupation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Army");

                    b.Property<Guid>("CityId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<Guid?>("OwnerId");

                    b.Property<int>("TurnId");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("TurnId", "CityId")
                        .IsUnique();

                    b.ToTable("CityOccupations");
                });

            modelBuilder.Entity("Fort.Database.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Amount");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<Guid>("SourceCityId");

                    b.Property<Guid>("TargetCityId");

                    b.Property<int>("TurnId");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("SourceCityId");

                    b.HasIndex("TargetCityId");

                    b.HasIndex("UserId");

                    b.HasIndex("TurnId", "SourceCityId", "TargetCityId")
                        .IsUnique();

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Fort.Database.Entities.Road", b =>
                {
                    b.Property<Guid>("SourceId");

                    b.Property<Guid>("TargetId");

                    b.HasKey("SourceId", "TargetId");

                    b.HasIndex("TargetId");

                    b.ToTable("Roads");
                });

            modelBuilder.Entity("Fort.Database.Entities.StartingPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Army");

                    b.Property<Guid>("CityId");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CityId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("StartingPositions");
                });

            modelBuilder.Entity("Fort.Database.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("ArmyStrengthCoef");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("ColorLight")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<double>("PopulationGrowthCoef");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Fort.Database.Entities.Turn", b =>
                {
                    b.Property<int>("Id");

                    b.Property<DateTime?>("EndsAt");

                    b.Property<DateTime?>("StartsAt");

                    b.HasKey("Id");

                    b.ToTable("Turns");
                });

            modelBuilder.Entity("Fort.Database.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp");

                    b.Property<string>("Email");

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(100);

                    b.Property<bool>("IsAdmin");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail");

                    b.Property<string>("NormalizedUserName");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<Guid>("TeamId");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TeamId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Fort.Database.Entities.CityOccupation", b =>
                {
                    b.HasOne("Fort.Database.Entities.City", "City")
                        .WithMany("CityOccupations")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fort.Database.Entities.User", "Owner")
                        .WithMany("CityOccupations")
                        .HasForeignKey("OwnerId");

                    b.HasOne("Fort.Database.Entities.Turn", "Turn")
                        .WithMany("CityOccupations")
                        .HasForeignKey("TurnId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Fort.Database.Entities.Order", b =>
                {
                    b.HasOne("Fort.Database.Entities.City", "SourceCity")
                        .WithMany("SourceForOrders")
                        .HasForeignKey("SourceCityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fort.Database.Entities.City", "TargetCity")
                        .WithMany("TargetForOrders")
                        .HasForeignKey("TargetCityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fort.Database.Entities.Turn", "Turn")
                        .WithMany("Orders")
                        .HasForeignKey("TurnId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fort.Database.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Fort.Database.Entities.Road", b =>
                {
                    b.HasOne("Fort.Database.Entities.City", "Source")
                        .WithMany("SourceForRoads")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fort.Database.Entities.City", "Target")
                        .WithMany("TargetForRoads")
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Fort.Database.Entities.StartingPosition", b =>
                {
                    b.HasOne("Fort.Database.Entities.City", "City")
                        .WithMany("StartingPositionFor")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fort.Database.Entities.User", "User")
                        .WithMany("StartingPositions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Fort.Database.Entities.User", b =>
                {
                    b.HasOne("Fort.Database.Entities.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
