// <auto-generated />
using System;
using Fort.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fort.Migrations
{
    [DbContext(typeof(FortDbContext))]
    partial class FortDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Fort.Database.Entities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("DefenceCoef");

                    b.Property<double>("PopulationGrowCoef");

                    b.Property<int>("X");

                    b.Property<int>("Y");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fd6aec80-dca3-4d64-b53c-18b7a93eb550"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 714,
                            Y = 124
                        },
                        new
                        {
                            Id = new Guid("834d65e5-7da3-4a42-871e-80f58d19b716"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 646,
                            Y = 467
                        },
                        new
                        {
                            Id = new Guid("d285bf5a-5439-4cb7-82fb-d6f59ee09af5"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 1572,
                            Y = 878
                        },
                        new
                        {
                            Id = new Guid("a5c86f14-024e-4e31-8b8a-8218e8d9daa9"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 431,
                            Y = 931
                        },
                        new
                        {
                            Id = new Guid("c8784857-2efe-4fad-b278-178b2b63e8db"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 544,
                            Y = 720
                        },
                        new
                        {
                            Id = new Guid("5039ec78-3834-4922-97d8-18785aa5b187"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 439,
                            Y = 646
                        },
                        new
                        {
                            Id = new Guid("95f92740-ee83-4054-b957-b01be3879d85"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 562,
                            Y = 624
                        },
                        new
                        {
                            Id = new Guid("49ef30e1-000d-4b64-a13d-3d1828be6781"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 698,
                            Y = 636
                        },
                        new
                        {
                            Id = new Guid("5acf8b05-b2ad-4e00-87a8-541d977717da"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 899,
                            Y = 798
                        },
                        new
                        {
                            Id = new Guid("7a0b25d1-2edd-49cd-a37c-ae5b6550aa89"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 1460,
                            Y = 574
                        },
                        new
                        {
                            Id = new Guid("c517921b-d088-45cd-a456-2c613a4feb9e"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 1624,
                            Y = 615
                        },
                        new
                        {
                            Id = new Guid("a75127b3-d2a7-4d8b-9f1d-986297ecece1"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 1476,
                            Y = 769
                        },
                        new
                        {
                            Id = new Guid("95e8d61e-068a-4374-9883-89224161c0d9"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 1441,
                            Y = 384
                        },
                        new
                        {
                            Id = new Guid("178b0049-509f-42da-9008-d49e5ea98142"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 1264,
                            Y = 415
                        },
                        new
                        {
                            Id = new Guid("20ae2fa2-907b-4f57-9d24-76dbc53972ff"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 1354,
                            Y = 313
                        },
                        new
                        {
                            Id = new Guid("f39e5b14-6633-4b17-b86d-b06076d0430c"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 1182,
                            Y = 228
                        },
                        new
                        {
                            Id = new Guid("36a87ae2-ab57-4b9e-965d-42e7dc4cf0f1"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 1238,
                            Y = 134
                        },
                        new
                        {
                            Id = new Guid("667d6946-47cf-4db6-bbc1-3c911bcc43f6"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 1445,
                            Y = 121
                        },
                        new
                        {
                            Id = new Guid("93205cf8-ec43-4464-b717-685442dcd641"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 1345,
                            Y = 182
                        },
                        new
                        {
                            Id = new Guid("e5f97401-4aff-4527-94af-c517f152156c"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 1154,
                            Y = 111
                        },
                        new
                        {
                            Id = new Guid("161e17f0-c63d-4793-b8c1-76d5d863518c"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 1001,
                            Y = 143
                        },
                        new
                        {
                            Id = new Guid("6e660a3f-7c0c-4597-91ae-2c877518da0a"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 1003,
                            Y = 315
                        },
                        new
                        {
                            Id = new Guid("9d4a6fc5-a5ea-4e07-8354-15dff81c356d"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 962,
                            Y = 464
                        },
                        new
                        {
                            Id = new Guid("4d814ee8-8d6a-49e2-93cb-71199f987f74"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 1019,
                            Y = 518
                        },
                        new
                        {
                            Id = new Guid("5fad7a28-61c8-46d3-916f-ead505a06e64"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 932,
                            Y = 586
                        },
                        new
                        {
                            Id = new Guid("1997df31-8e36-4166-91ba-423bcef19794"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 829,
                            Y = 507
                        },
                        new
                        {
                            Id = new Guid("b5a67442-19d8-471e-9c32-05a558db9fc7"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 905,
                            Y = 387
                        },
                        new
                        {
                            Id = new Guid("08c12c35-5306-49d3-bcdd-609f9213265a"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 805,
                            Y = 364
                        },
                        new
                        {
                            Id = new Guid("44e5bdfa-329a-41c4-aee2-a2ffc07211b7"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 1106,
                            Y = 299
                        },
                        new
                        {
                            Id = new Guid("27d4e3fc-e42e-4187-82d7-4f30e6ddb3e8"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 836,
                            Y = 143
                        },
                        new
                        {
                            Id = new Guid("b41531cb-c23e-4a7c-a149-ea86d942bfb2"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 784,
                            Y = 205
                        },
                        new
                        {
                            Id = new Guid("2431da6c-ddf9-4653-8344-d66de031955e"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 769,
                            Y = 286
                        },
                        new
                        {
                            Id = new Guid("ac8bf4f3-8842-4d6a-8b69-524fd944e19a"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 631,
                            Y = 307
                        },
                        new
                        {
                            Id = new Guid("8cbb321c-901e-4ccf-8981-88967a12481e"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 593,
                            Y = 110
                        },
                        new
                        {
                            Id = new Guid("f49609e4-10c0-4aa8-81dd-952d6a4319dd"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 480,
                            Y = 190
                        },
                        new
                        {
                            Id = new Guid("b253f54e-5458-45eb-b294-f6e4bde9053a"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 456,
                            Y = 79
                        },
                        new
                        {
                            Id = new Guid("cd3c9dc6-4ecf-4e07-bfbd-607a074edb5d"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 286,
                            Y = 119
                        },
                        new
                        {
                            Id = new Guid("a591ed84-9567-4d05-9a92-95e1b233b36c"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 150,
                            Y = 111
                        },
                        new
                        {
                            Id = new Guid("29e29893-dc9a-4958-b82b-f64ef83f9f7e"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 220,
                            Y = 182
                        },
                        new
                        {
                            Id = new Guid("353b3a8d-4598-45f5-ad5c-3bec55918665"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 372,
                            Y = 236
                        },
                        new
                        {
                            Id = new Guid("23aad6a1-0e21-4d93-a7e0-60d099793736"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 235,
                            Y = 299
                        },
                        new
                        {
                            Id = new Guid("487f8d99-99a3-4c58-90e1-e75615cc080c"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 193,
                            Y = 401
                        },
                        new
                        {
                            Id = new Guid("8db03f1c-ffd5-4895-8a64-cbdfd52c6aa1"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 328,
                            Y = 415
                        },
                        new
                        {
                            Id = new Guid("675a39ff-499d-4735-b54a-e7f8502edb33"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 428,
                            Y = 462
                        },
                        new
                        {
                            Id = new Guid("5d6a5e74-61cd-4f45-941d-e5bb8a81d66e"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 356,
                            Y = 548
                        },
                        new
                        {
                            Id = new Guid("965997a3-604a-46ea-a19a-ad8a9b3bc37e"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 418,
                            Y = 794
                        },
                        new
                        {
                            Id = new Guid("1b584abf-2d44-44fa-af36-2aaa97405e87"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 360,
                            Y = 680
                        },
                        new
                        {
                            Id = new Guid("7ef620a5-9462-452a-b779-ca343f470625"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 1616,
                            Y = 745
                        },
                        new
                        {
                            Id = new Guid("56f636ea-4898-4a14-be55-295f21fb663a"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 1753,
                            Y = 845
                        },
                        new
                        {
                            Id = new Guid("ec88c63d-214b-4980-9a0a-55d8d1505b2c"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 1554,
                            Y = 313
                        },
                        new
                        {
                            Id = new Guid("95037d18-01e5-483f-93ec-712f87298a76"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 889,
                            Y = 665
                        },
                        new
                        {
                            Id = new Guid("43398d9e-69c5-4203-a66b-5e8d67b82c90"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 506,
                            Y = 340
                        },
                        new
                        {
                            Id = new Guid("494df006-1afd-4b96-bcf3-9f0c4442965d"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 1079,
                            Y = 213
                        },
                        new
                        {
                            Id = new Guid("c68d7841-84c3-454a-9e2b-4c3d8e85e8da"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 335,
                            Y = 321
                        },
                        new
                        {
                            Id = new Guid("7aa73bb9-a0d3-4ce3-a1b4-21523befd582"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 144,
                            Y = 310
                        },
                        new
                        {
                            Id = new Guid("e315725c-fc53-4be6-9da1-1e259ab37748"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 1765,
                            Y = 518
                        },
                        new
                        {
                            Id = new Guid("da6b69f7-d94f-42ca-bad1-54f1906102c6"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 1067,
                            Y = 685
                        },
                        new
                        {
                            Id = new Guid("318137aa-fcf8-430a-b7b6-c98e2215510c"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 727,
                            Y = 438
                        },
                        new
                        {
                            Id = new Guid("aafbf738-869b-4f13-81a9-55847b242d7a"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 870,
                            Y = 223
                        },
                        new
                        {
                            Id = new Guid("6e591c23-5b60-4f81-ae3e-1c57e6c63962"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 1211,
                            Y = 556
                        },
                        new
                        {
                            Id = new Guid("87ae0df7-c6b5-4399-8386-f821b0340727"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 1757,
                            Y = 700
                        },
                        new
                        {
                            Id = new Guid("6bdf365d-d8c9-42f3-9fd6-8487d5704759"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 1106,
                            Y = 423
                        },
                        new
                        {
                            Id = new Guid("6e774576-1d08-43b8-beb8-e278f21679a1"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 473,
                            Y = 543
                        },
                        new
                        {
                            Id = new Guid("b890df70-d9b3-41f6-a624-be238c563e29"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 967,
                            Y = 213
                        },
                        new
                        {
                            Id = new Guid("cd9afdb5-3c6b-423e-9247-a8d26ba0a0a3"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 611,
                            Y = 962
                        },
                        new
                        {
                            Id = new Guid("208c67f5-ad51-490f-9f47-6b555ebbfc3a"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 1214,
                            Y = 671
                        },
                        new
                        {
                            Id = new Guid("74d20d91-a837-4f24-a9dd-4763e0caac4b"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 708,
                            Y = 348
                        },
                        new
                        {
                            Id = new Guid("a7861024-9eb4-4536-a0a9-e063022ae673"),
                            DefenceCoef = 1.0,
                            PopulationGrowCoef = 1.0,
                            X = 660,
                            Y = 800
                        });
                });

            modelBuilder.Entity("Fort.Database.Entities.CityOccupation", b =>
                {
                    b.Property<Guid>("CityId");

                    b.Property<int>("TurnId");

                    b.Property<int>("Army");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<Guid?>("OwnerId");

                    b.HasKey("CityId", "TurnId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("TurnId");

                    b.ToTable("CityOccupations");
                });

            modelBuilder.Entity("Fort.Database.Entities.Order", b =>
                {
                    b.Property<Guid>("StCityId");

                    b.Property<Guid>("NdCityId");

                    b.Property<int>("TurnId");

                    b.Property<bool>("StIsSource");

                    b.Property<int>("Amount");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<Guid>("UserId");

                    b.HasKey("StCityId", "NdCityId", "TurnId", "StIsSource");

                    b.HasIndex("TurnId");

                    b.HasIndex("UserId");

                    b.HasIndex("NdCityId", "TurnId");

                    b.HasIndex("StCityId", "TurnId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Fort.Database.Entities.Road", b =>
                {
                    b.Property<Guid>("StCityId");

                    b.Property<Guid>("NdCityId");

                    b.HasKey("StCityId", "NdCityId");

                    b.HasIndex("NdCityId");

                    b.ToTable("Roads");

                    b.HasData(
                        new
                        {
                            StCityId = new Guid("178b0049-509f-42da-9008-d49e5ea98142"),
                            NdCityId = new Guid("20ae2fa2-907b-4f57-9d24-76dbc53972ff")
                        },
                        new
                        {
                            StCityId = new Guid("7a0b25d1-2edd-49cd-a37c-ae5b6550aa89"),
                            NdCityId = new Guid("95e8d61e-068a-4374-9883-89224161c0d9")
                        },
                        new
                        {
                            StCityId = new Guid("178b0049-509f-42da-9008-d49e5ea98142"),
                            NdCityId = new Guid("7a0b25d1-2edd-49cd-a37c-ae5b6550aa89")
                        },
                        new
                        {
                            StCityId = new Guid("178b0049-509f-42da-9008-d49e5ea98142"),
                            NdCityId = new Guid("44e5bdfa-329a-41c4-aee2-a2ffc07211b7")
                        },
                        new
                        {
                            StCityId = new Guid("44e5bdfa-329a-41c4-aee2-a2ffc07211b7"),
                            NdCityId = new Guid("f39e5b14-6633-4b17-b86d-b06076d0430c")
                        },
                        new
                        {
                            StCityId = new Guid("494df006-1afd-4b96-bcf3-9f0c4442965d"),
                            NdCityId = new Guid("6e660a3f-7c0c-4597-91ae-2c877518da0a")
                        },
                        new
                        {
                            StCityId = new Guid("20ae2fa2-907b-4f57-9d24-76dbc53972ff"),
                            NdCityId = new Guid("95e8d61e-068a-4374-9883-89224161c0d9")
                        },
                        new
                        {
                            StCityId = new Guid("20ae2fa2-907b-4f57-9d24-76dbc53972ff"),
                            NdCityId = new Guid("f39e5b14-6633-4b17-b86d-b06076d0430c")
                        },
                        new
                        {
                            StCityId = new Guid("7a0b25d1-2edd-49cd-a37c-ae5b6550aa89"),
                            NdCityId = new Guid("c517921b-d088-45cd-a456-2c613a4feb9e")
                        },
                        new
                        {
                            StCityId = new Guid("7a0b25d1-2edd-49cd-a37c-ae5b6550aa89"),
                            NdCityId = new Guid("7ef620a5-9462-452a-b779-ca343f470625")
                        },
                        new
                        {
                            StCityId = new Guid("a75127b3-d2a7-4d8b-9f1d-986297ecece1"),
                            NdCityId = new Guid("d285bf5a-5439-4cb7-82fb-d6f59ee09af5")
                        },
                        new
                        {
                            StCityId = new Guid("56f636ea-4898-4a14-be55-295f21fb663a"),
                            NdCityId = new Guid("a75127b3-d2a7-4d8b-9f1d-986297ecece1")
                        },
                        new
                        {
                            StCityId = new Guid("e315725c-fc53-4be6-9da1-1e259ab37748"),
                            NdCityId = new Guid("ec88c63d-214b-4980-9a0a-55d8d1505b2c")
                        },
                        new
                        {
                            StCityId = new Guid("7ef620a5-9462-452a-b779-ca343f470625"),
                            NdCityId = new Guid("c517921b-d088-45cd-a456-2c613a4feb9e")
                        },
                        new
                        {
                            StCityId = new Guid("178b0049-509f-42da-9008-d49e5ea98142"),
                            NdCityId = new Guid("4d814ee8-8d6a-49e2-93cb-71199f987f74")
                        },
                        new
                        {
                            StCityId = new Guid("5acf8b05-b2ad-4e00-87a8-541d977717da"),
                            NdCityId = new Guid("95037d18-01e5-483f-93ec-712f87298a76")
                        },
                        new
                        {
                            StCityId = new Guid("1997df31-8e36-4166-91ba-423bcef19794"),
                            NdCityId = new Guid("95037d18-01e5-483f-93ec-712f87298a76")
                        },
                        new
                        {
                            StCityId = new Guid("5fad7a28-61c8-46d3-916f-ead505a06e64"),
                            NdCityId = new Guid("95037d18-01e5-483f-93ec-712f87298a76")
                        },
                        new
                        {
                            StCityId = new Guid("4d814ee8-8d6a-49e2-93cb-71199f987f74"),
                            NdCityId = new Guid("5fad7a28-61c8-46d3-916f-ead505a06e64")
                        },
                        new
                        {
                            StCityId = new Guid("1997df31-8e36-4166-91ba-423bcef19794"),
                            NdCityId = new Guid("9d4a6fc5-a5ea-4e07-8354-15dff81c356d")
                        },
                        new
                        {
                            StCityId = new Guid("667d6946-47cf-4db6-bbc1-3c911bcc43f6"),
                            NdCityId = new Guid("93205cf8-ec43-4464-b717-685442dcd641")
                        },
                        new
                        {
                            StCityId = new Guid("36a87ae2-ab57-4b9e-965d-42e7dc4cf0f1"),
                            NdCityId = new Guid("93205cf8-ec43-4464-b717-685442dcd641")
                        },
                        new
                        {
                            StCityId = new Guid("a75127b3-d2a7-4d8b-9f1d-986297ecece1"),
                            NdCityId = new Guid("da6b69f7-d94f-42ca-bad1-54f1906102c6")
                        },
                        new
                        {
                            StCityId = new Guid("49ef30e1-000d-4b64-a13d-3d1828be6781"),
                            NdCityId = new Guid("5acf8b05-b2ad-4e00-87a8-541d977717da")
                        },
                        new
                        {
                            StCityId = new Guid("5acf8b05-b2ad-4e00-87a8-541d977717da"),
                            NdCityId = new Guid("da6b69f7-d94f-42ca-bad1-54f1906102c6")
                        },
                        new
                        {
                            StCityId = new Guid("49ef30e1-000d-4b64-a13d-3d1828be6781"),
                            NdCityId = new Guid("95f92740-ee83-4054-b957-b01be3879d85")
                        },
                        new
                        {
                            StCityId = new Guid("4d814ee8-8d6a-49e2-93cb-71199f987f74"),
                            NdCityId = new Guid("9d4a6fc5-a5ea-4e07-8354-15dff81c356d")
                        },
                        new
                        {
                            StCityId = new Guid("44e5bdfa-329a-41c4-aee2-a2ffc07211b7"),
                            NdCityId = new Guid("9d4a6fc5-a5ea-4e07-8354-15dff81c356d")
                        },
                        new
                        {
                            StCityId = new Guid("494df006-1afd-4b96-bcf3-9f0c4442965d"),
                            NdCityId = new Guid("f39e5b14-6633-4b17-b86d-b06076d0430c")
                        },
                        new
                        {
                            StCityId = new Guid("36a87ae2-ab57-4b9e-965d-42e7dc4cf0f1"),
                            NdCityId = new Guid("e5f97401-4aff-4527-94af-c517f152156c")
                        },
                        new
                        {
                            StCityId = new Guid("161e17f0-c63d-4793-b8c1-76d5d863518c"),
                            NdCityId = new Guid("e5f97401-4aff-4527-94af-c517f152156c")
                        },
                        new
                        {
                            StCityId = new Guid("161e17f0-c63d-4793-b8c1-76d5d863518c"),
                            NdCityId = new Guid("494df006-1afd-4b96-bcf3-9f0c4442965d")
                        },
                        new
                        {
                            StCityId = new Guid("7a0b25d1-2edd-49cd-a37c-ae5b6550aa89"),
                            NdCityId = new Guid("a75127b3-d2a7-4d8b-9f1d-986297ecece1")
                        },
                        new
                        {
                            StCityId = new Guid("c517921b-d088-45cd-a456-2c613a4feb9e"),
                            NdCityId = new Guid("e315725c-fc53-4be6-9da1-1e259ab37748")
                        },
                        new
                        {
                            StCityId = new Guid("95e8d61e-068a-4374-9883-89224161c0d9"),
                            NdCityId = new Guid("ec88c63d-214b-4980-9a0a-55d8d1505b2c")
                        },
                        new
                        {
                            StCityId = new Guid("20ae2fa2-907b-4f57-9d24-76dbc53972ff"),
                            NdCityId = new Guid("ec88c63d-214b-4980-9a0a-55d8d1505b2c")
                        },
                        new
                        {
                            StCityId = new Guid("93205cf8-ec43-4464-b717-685442dcd641"),
                            NdCityId = new Guid("ec88c63d-214b-4980-9a0a-55d8d1505b2c")
                        },
                        new
                        {
                            StCityId = new Guid("93205cf8-ec43-4464-b717-685442dcd641"),
                            NdCityId = new Guid("f39e5b14-6633-4b17-b86d-b06076d0430c")
                        },
                        new
                        {
                            StCityId = new Guid("36a87ae2-ab57-4b9e-965d-42e7dc4cf0f1"),
                            NdCityId = new Guid("667d6946-47cf-4db6-bbc1-3c911bcc43f6")
                        },
                        new
                        {
                            StCityId = new Guid("667d6946-47cf-4db6-bbc1-3c911bcc43f6"),
                            NdCityId = new Guid("ec88c63d-214b-4980-9a0a-55d8d1505b2c")
                        },
                        new
                        {
                            StCityId = new Guid("20ae2fa2-907b-4f57-9d24-76dbc53972ff"),
                            NdCityId = new Guid("93205cf8-ec43-4464-b717-685442dcd641")
                        },
                        new
                        {
                            StCityId = new Guid("56f636ea-4898-4a14-be55-295f21fb663a"),
                            NdCityId = new Guid("d285bf5a-5439-4cb7-82fb-d6f59ee09af5")
                        },
                        new
                        {
                            StCityId = new Guid("56f636ea-4898-4a14-be55-295f21fb663a"),
                            NdCityId = new Guid("7ef620a5-9462-452a-b779-ca343f470625")
                        },
                        new
                        {
                            StCityId = new Guid("7ef620a5-9462-452a-b779-ca343f470625"),
                            NdCityId = new Guid("a75127b3-d2a7-4d8b-9f1d-986297ecece1")
                        },
                        new
                        {
                            StCityId = new Guid("95037d18-01e5-483f-93ec-712f87298a76"),
                            NdCityId = new Guid("da6b69f7-d94f-42ca-bad1-54f1906102c6")
                        },
                        new
                        {
                            StCityId = new Guid("5fad7a28-61c8-46d3-916f-ead505a06e64"),
                            NdCityId = new Guid("da6b69f7-d94f-42ca-bad1-54f1906102c6")
                        },
                        new
                        {
                            StCityId = new Guid("1997df31-8e36-4166-91ba-423bcef19794"),
                            NdCityId = new Guid("5fad7a28-61c8-46d3-916f-ead505a06e64")
                        },
                        new
                        {
                            StCityId = new Guid("1997df31-8e36-4166-91ba-423bcef19794"),
                            NdCityId = new Guid("49ef30e1-000d-4b64-a13d-3d1828be6781")
                        },
                        new
                        {
                            StCityId = new Guid("318137aa-fcf8-430a-b7b6-c98e2215510c"),
                            NdCityId = new Guid("95f92740-ee83-4054-b957-b01be3879d85")
                        },
                        new
                        {
                            StCityId = new Guid("318137aa-fcf8-430a-b7b6-c98e2215510c"),
                            NdCityId = new Guid("834d65e5-7da3-4a42-871e-80f58d19b716")
                        },
                        new
                        {
                            StCityId = new Guid("675a39ff-499d-4735-b54a-e7f8502edb33"),
                            NdCityId = new Guid("834d65e5-7da3-4a42-871e-80f58d19b716")
                        },
                        new
                        {
                            StCityId = new Guid("95f92740-ee83-4054-b957-b01be3879d85"),
                            NdCityId = new Guid("c8784857-2efe-4fad-b278-178b2b63e8db")
                        },
                        new
                        {
                            StCityId = new Guid("a5c86f14-024e-4e31-8b8a-8218e8d9daa9"),
                            NdCityId = new Guid("c8784857-2efe-4fad-b278-178b2b63e8db")
                        },
                        new
                        {
                            StCityId = new Guid("965997a3-604a-46ea-a19a-ad8a9b3bc37e"),
                            NdCityId = new Guid("a5c86f14-024e-4e31-8b8a-8218e8d9daa9")
                        },
                        new
                        {
                            StCityId = new Guid("1b584abf-2d44-44fa-af36-2aaa97405e87"),
                            NdCityId = new Guid("965997a3-604a-46ea-a19a-ad8a9b3bc37e")
                        },
                        new
                        {
                            StCityId = new Guid("5039ec78-3834-4922-97d8-18785aa5b187"),
                            NdCityId = new Guid("965997a3-604a-46ea-a19a-ad8a9b3bc37e")
                        },
                        new
                        {
                            StCityId = new Guid("965997a3-604a-46ea-a19a-ad8a9b3bc37e"),
                            NdCityId = new Guid("c8784857-2efe-4fad-b278-178b2b63e8db")
                        },
                        new
                        {
                            StCityId = new Guid("1b584abf-2d44-44fa-af36-2aaa97405e87"),
                            NdCityId = new Guid("5039ec78-3834-4922-97d8-18785aa5b187")
                        },
                        new
                        {
                            StCityId = new Guid("5039ec78-3834-4922-97d8-18785aa5b187"),
                            NdCityId = new Guid("95f92740-ee83-4054-b957-b01be3879d85")
                        },
                        new
                        {
                            StCityId = new Guid("1b584abf-2d44-44fa-af36-2aaa97405e87"),
                            NdCityId = new Guid("5d6a5e74-61cd-4f45-941d-e5bb8a81d66e")
                        },
                        new
                        {
                            StCityId = new Guid("5039ec78-3834-4922-97d8-18785aa5b187"),
                            NdCityId = new Guid("5d6a5e74-61cd-4f45-941d-e5bb8a81d66e")
                        },
                        new
                        {
                            StCityId = new Guid("5d6a5e74-61cd-4f45-941d-e5bb8a81d66e"),
                            NdCityId = new Guid("675a39ff-499d-4735-b54a-e7f8502edb33")
                        },
                        new
                        {
                            StCityId = new Guid("5039ec78-3834-4922-97d8-18785aa5b187"),
                            NdCityId = new Guid("834d65e5-7da3-4a42-871e-80f58d19b716")
                        },
                        new
                        {
                            StCityId = new Guid("5d6a5e74-61cd-4f45-941d-e5bb8a81d66e"),
                            NdCityId = new Guid("8db03f1c-ffd5-4895-8a64-cbdfd52c6aa1")
                        },
                        new
                        {
                            StCityId = new Guid("675a39ff-499d-4735-b54a-e7f8502edb33"),
                            NdCityId = new Guid("8db03f1c-ffd5-4895-8a64-cbdfd52c6aa1")
                        },
                        new
                        {
                            StCityId = new Guid("487f8d99-99a3-4c58-90e1-e75615cc080c"),
                            NdCityId = new Guid("8db03f1c-ffd5-4895-8a64-cbdfd52c6aa1")
                        },
                        new
                        {
                            StCityId = new Guid("487f8d99-99a3-4c58-90e1-e75615cc080c"),
                            NdCityId = new Guid("7aa73bb9-a0d3-4ce3-a1b4-21523befd582")
                        },
                        new
                        {
                            StCityId = new Guid("23aad6a1-0e21-4d93-a7e0-60d099793736"),
                            NdCityId = new Guid("7aa73bb9-a0d3-4ce3-a1b4-21523befd582")
                        },
                        new
                        {
                            StCityId = new Guid("23aad6a1-0e21-4d93-a7e0-60d099793736"),
                            NdCityId = new Guid("c68d7841-84c3-454a-9e2b-4c3d8e85e8da")
                        },
                        new
                        {
                            StCityId = new Guid("8db03f1c-ffd5-4895-8a64-cbdfd52c6aa1"),
                            NdCityId = new Guid("c68d7841-84c3-454a-9e2b-4c3d8e85e8da")
                        },
                        new
                        {
                            StCityId = new Guid("29e29893-dc9a-4958-b82b-f64ef83f9f7e"),
                            NdCityId = new Guid("7aa73bb9-a0d3-4ce3-a1b4-21523befd582")
                        },
                        new
                        {
                            StCityId = new Guid("29e29893-dc9a-4958-b82b-f64ef83f9f7e"),
                            NdCityId = new Guid("a591ed84-9567-4d05-9a92-95e1b233b36c")
                        },
                        new
                        {
                            StCityId = new Guid("a591ed84-9567-4d05-9a92-95e1b233b36c"),
                            NdCityId = new Guid("cd3c9dc6-4ecf-4e07-bfbd-607a074edb5d")
                        },
                        new
                        {
                            StCityId = new Guid("29e29893-dc9a-4958-b82b-f64ef83f9f7e"),
                            NdCityId = new Guid("cd3c9dc6-4ecf-4e07-bfbd-607a074edb5d")
                        },
                        new
                        {
                            StCityId = new Guid("29e29893-dc9a-4958-b82b-f64ef83f9f7e"),
                            NdCityId = new Guid("353b3a8d-4598-45f5-ad5c-3bec55918665")
                        },
                        new
                        {
                            StCityId = new Guid("23aad6a1-0e21-4d93-a7e0-60d099793736"),
                            NdCityId = new Guid("29e29893-dc9a-4958-b82b-f64ef83f9f7e")
                        },
                        new
                        {
                            StCityId = new Guid("29e29893-dc9a-4958-b82b-f64ef83f9f7e"),
                            NdCityId = new Guid("c68d7841-84c3-454a-9e2b-4c3d8e85e8da")
                        },
                        new
                        {
                            StCityId = new Guid("353b3a8d-4598-45f5-ad5c-3bec55918665"),
                            NdCityId = new Guid("cd3c9dc6-4ecf-4e07-bfbd-607a074edb5d")
                        },
                        new
                        {
                            StCityId = new Guid("b253f54e-5458-45eb-b294-f6e4bde9053a"),
                            NdCityId = new Guid("cd3c9dc6-4ecf-4e07-bfbd-607a074edb5d")
                        },
                        new
                        {
                            StCityId = new Guid("b253f54e-5458-45eb-b294-f6e4bde9053a"),
                            NdCityId = new Guid("f49609e4-10c0-4aa8-81dd-952d6a4319dd")
                        },
                        new
                        {
                            StCityId = new Guid("353b3a8d-4598-45f5-ad5c-3bec55918665"),
                            NdCityId = new Guid("f49609e4-10c0-4aa8-81dd-952d6a4319dd")
                        },
                        new
                        {
                            StCityId = new Guid("43398d9e-69c5-4203-a66b-5e8d67b82c90"),
                            NdCityId = new Guid("c68d7841-84c3-454a-9e2b-4c3d8e85e8da")
                        },
                        new
                        {
                            StCityId = new Guid("353b3a8d-4598-45f5-ad5c-3bec55918665"),
                            NdCityId = new Guid("43398d9e-69c5-4203-a66b-5e8d67b82c90")
                        },
                        new
                        {
                            StCityId = new Guid("43398d9e-69c5-4203-a66b-5e8d67b82c90"),
                            NdCityId = new Guid("675a39ff-499d-4735-b54a-e7f8502edb33")
                        },
                        new
                        {
                            StCityId = new Guid("43398d9e-69c5-4203-a66b-5e8d67b82c90"),
                            NdCityId = new Guid("834d65e5-7da3-4a42-871e-80f58d19b716")
                        },
                        new
                        {
                            StCityId = new Guid("43398d9e-69c5-4203-a66b-5e8d67b82c90"),
                            NdCityId = new Guid("ac8bf4f3-8842-4d6a-8b69-524fd944e19a")
                        },
                        new
                        {
                            StCityId = new Guid("ac8bf4f3-8842-4d6a-8b69-524fd944e19a"),
                            NdCityId = new Guid("f49609e4-10c0-4aa8-81dd-952d6a4319dd")
                        },
                        new
                        {
                            StCityId = new Guid("8cbb321c-901e-4ccf-8981-88967a12481e"),
                            NdCityId = new Guid("b253f54e-5458-45eb-b294-f6e4bde9053a")
                        },
                        new
                        {
                            StCityId = new Guid("8cbb321c-901e-4ccf-8981-88967a12481e"),
                            NdCityId = new Guid("f49609e4-10c0-4aa8-81dd-952d6a4319dd")
                        },
                        new
                        {
                            StCityId = new Guid("8cbb321c-901e-4ccf-8981-88967a12481e"),
                            NdCityId = new Guid("fd6aec80-dca3-4d64-b53c-18b7a93eb550")
                        },
                        new
                        {
                            StCityId = new Guid("b41531cb-c23e-4a7c-a149-ea86d942bfb2"),
                            NdCityId = new Guid("f49609e4-10c0-4aa8-81dd-952d6a4319dd")
                        },
                        new
                        {
                            StCityId = new Guid("8cbb321c-901e-4ccf-8981-88967a12481e"),
                            NdCityId = new Guid("b41531cb-c23e-4a7c-a149-ea86d942bfb2")
                        },
                        new
                        {
                            StCityId = new Guid("2431da6c-ddf9-4653-8344-d66de031955e"),
                            NdCityId = new Guid("ac8bf4f3-8842-4d6a-8b69-524fd944e19a")
                        },
                        new
                        {
                            StCityId = new Guid("27d4e3fc-e42e-4187-82d7-4f30e6ddb3e8"),
                            NdCityId = new Guid("fd6aec80-dca3-4d64-b53c-18b7a93eb550")
                        },
                        new
                        {
                            StCityId = new Guid("b41531cb-c23e-4a7c-a149-ea86d942bfb2"),
                            NdCityId = new Guid("fd6aec80-dca3-4d64-b53c-18b7a93eb550")
                        },
                        new
                        {
                            StCityId = new Guid("27d4e3fc-e42e-4187-82d7-4f30e6ddb3e8"),
                            NdCityId = new Guid("aafbf738-869b-4f13-81a9-55847b242d7a")
                        },
                        new
                        {
                            StCityId = new Guid("27d4e3fc-e42e-4187-82d7-4f30e6ddb3e8"),
                            NdCityId = new Guid("b41531cb-c23e-4a7c-a149-ea86d942bfb2")
                        },
                        new
                        {
                            StCityId = new Guid("08c12c35-5306-49d3-bcdd-609f9213265a"),
                            NdCityId = new Guid("2431da6c-ddf9-4653-8344-d66de031955e")
                        },
                        new
                        {
                            StCityId = new Guid("08c12c35-5306-49d3-bcdd-609f9213265a"),
                            NdCityId = new Guid("318137aa-fcf8-430a-b7b6-c98e2215510c")
                        },
                        new
                        {
                            StCityId = new Guid("08c12c35-5306-49d3-bcdd-609f9213265a"),
                            NdCityId = new Guid("b5a67442-19d8-471e-9c32-05a558db9fc7")
                        },
                        new
                        {
                            StCityId = new Guid("2431da6c-ddf9-4653-8344-d66de031955e"),
                            NdCityId = new Guid("b41531cb-c23e-4a7c-a149-ea86d942bfb2")
                        },
                        new
                        {
                            StCityId = new Guid("6e660a3f-7c0c-4597-91ae-2c877518da0a"),
                            NdCityId = new Guid("aafbf738-869b-4f13-81a9-55847b242d7a")
                        },
                        new
                        {
                            StCityId = new Guid("08c12c35-5306-49d3-bcdd-609f9213265a"),
                            NdCityId = new Guid("aafbf738-869b-4f13-81a9-55847b242d7a")
                        },
                        new
                        {
                            StCityId = new Guid("161e17f0-c63d-4793-b8c1-76d5d863518c"),
                            NdCityId = new Guid("27d4e3fc-e42e-4187-82d7-4f30e6ddb3e8")
                        },
                        new
                        {
                            StCityId = new Guid("aafbf738-869b-4f13-81a9-55847b242d7a"),
                            NdCityId = new Guid("b5a67442-19d8-471e-9c32-05a558db9fc7")
                        },
                        new
                        {
                            StCityId = new Guid("6e660a3f-7c0c-4597-91ae-2c877518da0a"),
                            NdCityId = new Guid("b5a67442-19d8-471e-9c32-05a558db9fc7")
                        },
                        new
                        {
                            StCityId = new Guid("1997df31-8e36-4166-91ba-423bcef19794"),
                            NdCityId = new Guid("318137aa-fcf8-430a-b7b6-c98e2215510c")
                        },
                        new
                        {
                            StCityId = new Guid("9d4a6fc5-a5ea-4e07-8354-15dff81c356d"),
                            NdCityId = new Guid("b5a67442-19d8-471e-9c32-05a558db9fc7")
                        },
                        new
                        {
                            StCityId = new Guid("1997df31-8e36-4166-91ba-423bcef19794"),
                            NdCityId = new Guid("b5a67442-19d8-471e-9c32-05a558db9fc7")
                        },
                        new
                        {
                            StCityId = new Guid("834d65e5-7da3-4a42-871e-80f58d19b716"),
                            NdCityId = new Guid("ac8bf4f3-8842-4d6a-8b69-524fd944e19a")
                        },
                        new
                        {
                            StCityId = new Guid("178b0049-509f-42da-9008-d49e5ea98142"),
                            NdCityId = new Guid("6e591c23-5b60-4f81-ae3e-1c57e6c63962")
                        },
                        new
                        {
                            StCityId = new Guid("4d814ee8-8d6a-49e2-93cb-71199f987f74"),
                            NdCityId = new Guid("6e591c23-5b60-4f81-ae3e-1c57e6c63962")
                        },
                        new
                        {
                            StCityId = new Guid("6e591c23-5b60-4f81-ae3e-1c57e6c63962"),
                            NdCityId = new Guid("da6b69f7-d94f-42ca-bad1-54f1906102c6")
                        },
                        new
                        {
                            StCityId = new Guid("6e591c23-5b60-4f81-ae3e-1c57e6c63962"),
                            NdCityId = new Guid("a75127b3-d2a7-4d8b-9f1d-986297ecece1")
                        },
                        new
                        {
                            StCityId = new Guid("6e591c23-5b60-4f81-ae3e-1c57e6c63962"),
                            NdCityId = new Guid("7a0b25d1-2edd-49cd-a37c-ae5b6550aa89")
                        },
                        new
                        {
                            StCityId = new Guid("834d65e5-7da3-4a42-871e-80f58d19b716"),
                            NdCityId = new Guid("95f92740-ee83-4054-b957-b01be3879d85")
                        },
                        new
                        {
                            StCityId = new Guid("7aa73bb9-a0d3-4ce3-a1b4-21523befd582"),
                            NdCityId = new Guid("a591ed84-9567-4d05-9a92-95e1b233b36c")
                        },
                        new
                        {
                            StCityId = new Guid("e5f97401-4aff-4527-94af-c517f152156c"),
                            NdCityId = new Guid("f39e5b14-6633-4b17-b86d-b06076d0430c")
                        },
                        new
                        {
                            StCityId = new Guid("494df006-1afd-4b96-bcf3-9f0c4442965d"),
                            NdCityId = new Guid("e5f97401-4aff-4527-94af-c517f152156c")
                        },
                        new
                        {
                            StCityId = new Guid("36a87ae2-ab57-4b9e-965d-42e7dc4cf0f1"),
                            NdCityId = new Guid("f39e5b14-6633-4b17-b86d-b06076d0430c")
                        },
                        new
                        {
                            StCityId = new Guid("675a39ff-499d-4735-b54a-e7f8502edb33"),
                            NdCityId = new Guid("6e774576-1d08-43b8-beb8-e278f21679a1")
                        },
                        new
                        {
                            StCityId = new Guid("5d6a5e74-61cd-4f45-941d-e5bb8a81d66e"),
                            NdCityId = new Guid("6e774576-1d08-43b8-beb8-e278f21679a1")
                        },
                        new
                        {
                            StCityId = new Guid("6e774576-1d08-43b8-beb8-e278f21679a1"),
                            NdCityId = new Guid("834d65e5-7da3-4a42-871e-80f58d19b716")
                        },
                        new
                        {
                            StCityId = new Guid("2431da6c-ddf9-4653-8344-d66de031955e"),
                            NdCityId = new Guid("aafbf738-869b-4f13-81a9-55847b242d7a")
                        },
                        new
                        {
                            StCityId = new Guid("161e17f0-c63d-4793-b8c1-76d5d863518c"),
                            NdCityId = new Guid("b890df70-d9b3-41f6-a624-be238c563e29")
                        },
                        new
                        {
                            StCityId = new Guid("44e5bdfa-329a-41c4-aee2-a2ffc07211b7"),
                            NdCityId = new Guid("6bdf365d-d8c9-42f3-9fd6-8487d5704759")
                        },
                        new
                        {
                            StCityId = new Guid("87ae0df7-c6b5-4399-8386-f821b0340727"),
                            NdCityId = new Guid("c517921b-d088-45cd-a456-2c613a4feb9e")
                        },
                        new
                        {
                            StCityId = new Guid("7ef620a5-9462-452a-b779-ca343f470625"),
                            NdCityId = new Guid("87ae0df7-c6b5-4399-8386-f821b0340727")
                        },
                        new
                        {
                            StCityId = new Guid("87ae0df7-c6b5-4399-8386-f821b0340727"),
                            NdCityId = new Guid("e315725c-fc53-4be6-9da1-1e259ab37748")
                        },
                        new
                        {
                            StCityId = new Guid("56f636ea-4898-4a14-be55-295f21fb663a"),
                            NdCityId = new Guid("87ae0df7-c6b5-4399-8386-f821b0340727")
                        },
                        new
                        {
                            StCityId = new Guid("a5c86f14-024e-4e31-8b8a-8218e8d9daa9"),
                            NdCityId = new Guid("cd9afdb5-3c6b-423e-9247-a8d26ba0a0a3")
                        },
                        new
                        {
                            StCityId = new Guid("5acf8b05-b2ad-4e00-87a8-541d977717da"),
                            NdCityId = new Guid("cd9afdb5-3c6b-423e-9247-a8d26ba0a0a3")
                        },
                        new
                        {
                            StCityId = new Guid("208c67f5-ad51-490f-9f47-6b555ebbfc3a"),
                            NdCityId = new Guid("6e591c23-5b60-4f81-ae3e-1c57e6c63962")
                        },
                        new
                        {
                            StCityId = new Guid("74d20d91-a837-4f24-a9dd-4763e0caac4b"),
                            NdCityId = new Guid("ac8bf4f3-8842-4d6a-8b69-524fd944e19a")
                        },
                        new
                        {
                            StCityId = new Guid("49ef30e1-000d-4b64-a13d-3d1828be6781"),
                            NdCityId = new Guid("a7861024-9eb4-4536-a0a9-e063022ae673")
                        });
                });

            modelBuilder.Entity("Fort.Database.Entities.StartingPosition", b =>
                {
                    b.Property<Guid>("CityId");

                    b.Property<int?>("Army");

                    b.Property<Guid>("UserId");

                    b.HasKey("CityId");

                    b.HasIndex("UserId");

                    b.ToTable("StartingPositions");

                    b.HasData(
                        new
                        {
                            CityId = new Guid("a591ed84-9567-4d05-9a92-95e1b233b36c"),
                            Army = 15,
                            UserId = new Guid("08d7d312-5b73-86fb-7e7c-5d6b08a519b0")
                        },
                        new
                        {
                            CityId = new Guid("2431da6c-ddf9-4653-8344-d66de031955e"),
                            Army = 15,
                            UserId = new Guid("8c1d1996-4d41-4892-82d9-29d00b986958")
                        },
                        new
                        {
                            CityId = new Guid("aafbf738-869b-4f13-81a9-55847b242d7a"),
                            Army = 15,
                            UserId = new Guid("07af142f-2ba3-4499-b9a7-d3347920b04a")
                        });
                });

            modelBuilder.Entity("Fort.Database.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("ArmyStrengthCoef");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("ColorLight")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<double>("PopulationGrowthCoef");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4b44b52e-d354-4600-bb4a-ba87db0c6bc5"),
                            ArmyStrengthCoef = 1.0,
                            Color = "#52834b",
                            ColorLight = "#9dc498",
                            PopulationGrowthCoef = 1.0
                        },
                        new
                        {
                            Id = new Guid("3541fb45-b40f-4199-a860-2f731c3341a8"),
                            ArmyStrengthCoef = 1.0,
                            Color = "#4b7183",
                            ColorLight = "#98b6c4",
                            PopulationGrowthCoef = 1.0
                        },
                        new
                        {
                            Id = new Guid("2ebcc534-9b62-448b-b8cb-7e74f7d9c8b6"),
                            ArmyStrengthCoef = 1.0,
                            Color = "#83824b",
                            ColorLight = "#c4c498",
                            PopulationGrowthCoef = 1.0
                        });
                });

            modelBuilder.Entity("Fort.Database.Entities.Turn", b =>
                {
                    b.Property<int>("Id");

                    b.Property<DateTime?>("EndsAt");

                    b.Property<DateTime?>("StartsAt");

                    b.HasKey("Id");

                    b.ToTable("Turns");
                });

            modelBuilder.Entity("Fort.Database.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp");

                    b.Property<string>("Email");

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(100);

                    b.Property<bool>("IsAdmin");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail");

                    b.Property<string>("NormalizedUserName");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<Guid>("TeamId");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TeamId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("08d7d312-5b73-86fb-7e7c-5d6b08a519b0"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f0d27d0f-078e-4edd-8732-10a8ae6cbf5a",
                            Email = "a",
                            EmailConfirmed = false,
                            IsAdmin = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFuzvZx1UOwIMC9i6XWUw2itbgoa2/Fg/tUSCH8NhJdL9MPSur/ZN/wgiEVBQnBmyw==",
                            PhoneNumberConfirmed = false,
                            TeamId = new Guid("4b44b52e-d354-4600-bb4a-ba87db0c6bc5"),
                            TwoFactorEnabled = false,
                            UserName = "A"
                        },
                        new
                        {
                            Id = new Guid("8c1d1996-4d41-4892-82d9-29d00b986958"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "932a8c18-5e96-4db3-926e-f52142d6c5d6",
                            Email = "b",
                            EmailConfirmed = false,
                            IsAdmin = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEJCNVHZeDNTSqJjqKFlp7CRZEBMDkQATuj7FKxvtpO2/q3w8xORbQzUF1bZ/FKr2cA==",
                            PhoneNumberConfirmed = false,
                            TeamId = new Guid("3541fb45-b40f-4199-a860-2f731c3341a8"),
                            TwoFactorEnabled = false,
                            UserName = "B"
                        },
                        new
                        {
                            Id = new Guid("07af142f-2ba3-4499-b9a7-d3347920b04a"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bf523aed-8cd4-4793-a602-3bce8f334a95",
                            Email = "c",
                            EmailConfirmed = false,
                            IsAdmin = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAECxoze2Fh8lG09895QNaWlpHs5NX0RCQTWwPoLaj+FDp7xvpBbnIGs/ocZ53v7yJSg==",
                            PhoneNumberConfirmed = false,
                            TeamId = new Guid("2ebcc534-9b62-448b-b8cb-7e74f7d9c8b6"),
                            TwoFactorEnabled = false,
                            UserName = "C"
                        });
                });

            modelBuilder.Entity("Fort.Database.Entities.CityOccupation", b =>
                {
                    b.HasOne("Fort.Database.Entities.City", "City")
                        .WithMany("CityOccupations")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fort.Database.Entities.User", "Owner")
                        .WithMany("CityOccupations")
                        .HasForeignKey("OwnerId");

                    b.HasOne("Fort.Database.Entities.Turn", "Turn")
                        .WithMany("CityOccupations")
                        .HasForeignKey("TurnId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Fort.Database.Entities.Order", b =>
                {
                    b.HasOne("Fort.Database.Entities.City", "NdCity")
                        .WithMany("NdForOrders")
                        .HasForeignKey("NdCityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fort.Database.Entities.City", "StCity")
                        .WithMany("StForOrders")
                        .HasForeignKey("StCityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fort.Database.Entities.Turn", "Turn")
                        .WithMany("Orders")
                        .HasForeignKey("TurnId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fort.Database.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fort.Database.Entities.CityOccupation", "NdCityOccupation")
                        .WithMany("NdForOrders")
                        .HasForeignKey("NdCityId", "TurnId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fort.Database.Entities.Road", "Road")
                        .WithMany("Orders")
                        .HasForeignKey("StCityId", "NdCityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fort.Database.Entities.CityOccupation", "StCityOccupation")
                        .WithMany("StForOrders")
                        .HasForeignKey("StCityId", "TurnId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Fort.Database.Entities.Road", b =>
                {
                    b.HasOne("Fort.Database.Entities.City", "NdCity")
                        .WithMany("NdForRoads")
                        .HasForeignKey("NdCityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fort.Database.Entities.City", "StCity")
                        .WithMany("StForRoads")
                        .HasForeignKey("StCityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Fort.Database.Entities.StartingPosition", b =>
                {
                    b.HasOne("Fort.Database.Entities.City", "City")
                        .WithMany("StartingPositionFor")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fort.Database.Entities.User", "User")
                        .WithMany("StartingPositions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Fort.Database.Entities.User", b =>
                {
                    b.HasOne("Fort.Database.Entities.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
